NAME = test	
SRCS = \
	Config.cpp\
	JsonData.cpp\
	JsonParser.cpp\
	Cgi.cpp\
	Client.cpp\
	EventHandler.cpp\
	File.cpp\
	Host.cpp\
	Location.cpp\
	Request.cpp\
	Response.cpp\
	Server.cpp\
	Util.cpp\
	Webserver.cpp\
	main.cpp

include ./template.mk